// <auto-generated />
using System;
using FilmMoi.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmMoi.Domain.Migrations
{
    [DbContext(typeof(FilmMoiContext))]
    [Migration("20240706130933_g")]
    partial class g
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Actors", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DeletedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ID = new Guid("7677bb7f-f9aa-4738-a61d-b52427d9dd62"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 20, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7087), new TimeSpan(0, 7, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Dob = new DateTime(1997, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "actor1.jpg",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Kirigaya Kazuto",
                            Nationality = "Japan"
                        },
                        new
                        {
                            ID = new Guid("794b3996-aac6-437e-87c6-197fde46149d"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 20, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7155), new TimeSpan(0, 7, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Dob = new DateTime(1998, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "actor2.jpg",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Asuna Yuuki",
                            Nationality = "Japan"
                        },
                        new
                        {
                            ID = new Guid("e7ec9630-52da-4e31-9700-afe4627d672a"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 20, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7164), new TimeSpan(0, 7, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Dob = new DateTime(1990, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "actor3.jpg",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Levi Ackerman",
                            Nationality = "Japan"
                        },
                        new
                        {
                            ID = new Guid("7a118f30-af35-4364-a288-098704a94e08"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 20, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7171), new TimeSpan(0, 7, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Dob = new DateTime(1979, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "actor4.jpg",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Hermione Granger",
                            Nationality = "America"
                        },
                        new
                        {
                            ID = new Guid("cc140641-ef72-4918-a94f-79bc30755d62"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 20, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7194), new TimeSpan(0, 7, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Dob = new DateTime(1984, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "actor5.jpg",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Scarlett Johansson",
                            Nationality = "America"
                        });
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Comments", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment_text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ID_Film")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_User")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("ID_Film");

                    b.HasIndex("ID_User");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Episodes", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Film_Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ID_Film")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_Film");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.FilmActors", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ID_ACtor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_Film")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("ID_ACtor");

                    b.HasIndex("ID_Film");

                    b.ToTable("FilmActors");

                    b.HasData(
                        new
                        {
                            ID = new Guid("82b4ff19-b8db-45e0-b10c-fe1ade8f989e"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(8353), new TimeSpan(0, 0, 0, 0, 0)),
                            ID_ACtor = new Guid("7677bb7f-f9aa-4738-a61d-b52427d9dd62"),
                            ID_Film = new Guid("98236a61-4d91-42fe-b956-fd64fb14ddc5"),
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ID = new Guid("b8d9e65a-be9f-46b1-ac54-d83aaa5b63cd"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(8364), new TimeSpan(0, 0, 0, 0, 0)),
                            ID_ACtor = new Guid("794b3996-aac6-437e-87c6-197fde46149d"),
                            ID_Film = new Guid("98236a61-4d91-42fe-b956-fd64fb14ddc5"),
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Films", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("AvgDuration")
                        .HasColumnType("time");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DeletedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalEpisode")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            ID = new Guid("98236a61-4d91-42fe-b956-fd64fb14ddc5"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7271), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Anime cute",
                            Director = "Reki Kawahara",
                            Image = "series-1.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Sword Art Online",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("d8a2e1e2-5d8c-4c4c-bf5f-9a7d32de0a2a"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7298), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Frank Darabont",
                            Image = "series-2.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "The Shawshank Redemption",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("f5f7a014-9d4e-4c2e-a0b6-9b063f2e8f55"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7308), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Christopher Nolan",
                            Image = "series-3.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Inception",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("7b6c8b8f-70da-4e89-9971-2f1a8e7f9b56"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7332), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Quentin Tarantino",
                            Image = "series-4.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Pulp Fiction",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("3d9a9d16-1b45-4a9b-8f7e-e3f0e0d8e3b9"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7340), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Christopher Nolan",
                            Image = "movie-1.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "The Dark Knight",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("74dc0bc7-d385-46cb-a143-2831b344fda7"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7411), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director0",
                            Image = "movie-1.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film0",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("4af30cd9-d405-4911-8a5f-bfb350c65ea7"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7543), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director1",
                            Image = "movie-4.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film1",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("4b601c93-f48c-42ed-a782-03de913a2a75"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7558), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director2",
                            Image = "movie-2.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film2",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("0914172c-19e3-417d-bedf-fc19400967d9"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7575), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director3",
                            Image = "movie-5.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film3",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("91aaf245-b8b7-4b6f-8b87-19eb4a01fac8"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7587), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director4",
                            Image = "movie-1.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film4",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("14cc5350-f7ac-41ab-b94c-bece100dfa88"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7607), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director5",
                            Image = "movie-5.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film5",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("fbc98e0c-4e4b-442b-848d-72d69148d6c2"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7618), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director6",
                            Image = "movie-1.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film6",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("0853c5a8-de68-471b-8bbf-343abdcb7b7c"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7629), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director7",
                            Image = "movie-3.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film7",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("92e31d89-0a40-4933-9202-2d62af114369"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7645), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director8",
                            Image = "movie-3.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film8",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("bfa7cf54-986d-4008-9eee-c250076c6878"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7657), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director9",
                            Image = "movie-1.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film9",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("9cbfa2c9-ed94-4823-8e69-deddc159bcdf"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7667), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director10",
                            Image = "movie-3.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film10",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("ac5faa37-c702-4ea8-8145-3e409761ca58"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7683), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director11",
                            Image = "movie-1.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film11",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("c717ae9d-c5a2-4220-a2e4-4e95a37a0e43"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7693), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director12",
                            Image = "movie-1.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film12",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("f6bea5a0-35ad-4394-b79b-9801943e9db4"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7707), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director13",
                            Image = "movie-5.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film13",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("afabc6a9-0fcd-4727-a6bb-0ae4ee7ce35a"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7734), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director14",
                            Image = "movie-5.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film14",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("4252a101-b52a-40a6-b3e7-4165cf2dc96e"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7746), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director15",
                            Image = "movie-4.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film15",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("a87fb86e-1e1a-47b4-9f66-69359c976577"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7764), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director16",
                            Image = "movie-4.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film16",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("8612fceb-a08b-472b-9fed-e14c9f2f0c92"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7778), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director17",
                            Image = "movie-1.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film17",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("2af42872-85b8-432e-b859-663cc5b41374"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7789), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director18",
                            Image = "movie-3.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film18",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("8ead14a4-40f3-41c2-b724-5e9abab15a9b"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7804), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director19",
                            Image = "movie-7.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film19",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("b06c358d-ac6c-40ac-ac5c-904aa049e9b8"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7815), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director20",
                            Image = "movie-6.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film20",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("f7a130cd-7fa6-44be-a7f8-af2adc705431"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7829), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director21",
                            Image = "movie-2.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film21",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("5e97ac13-1f35-4028-aa9f-4c8fc7560743"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7840), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director22",
                            Image = "movie-3.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film22",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("294f85fb-0ae3-4adb-9132-9e1c36a9cbfa"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7849), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director23",
                            Image = "movie-2.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film23",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("27a69a68-4fb5-49c7-bfc0-f5edc5d852b5"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7862), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director24",
                            Image = "movie-2.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film24",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("2eecc00d-341f-4a92-8d5f-85350d3250d8"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7872), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director25",
                            Image = "movie-2.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film25",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("f8320493-1db0-456a-90f6-c654b1721c67"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7881), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director26",
                            Image = "movie-6.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film26",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("5509dc9a-f83d-4276-be82-2a655271356b"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7896), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director27",
                            Image = "movie-6.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film27",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("f04401f4-41aa-4cca-87d0-c72eff41aa5e"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7906), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director28",
                            Image = "movie-5.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film28",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        },
                        new
                        {
                            ID = new Guid("9d440332-b5c9-4710-9859-a4791764abc6"),
                            AvgDuration = new TimeSpan(0, 0, 0, 0, 0),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(7936), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Movie cute",
                            Director = "Director29",
                            Image = "movie-2.png",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Film29",
                            Status = 1,
                            TotalEpisode = 0,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.GenreFilms", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ID_Film")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_Genre")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("ID_Film");

                    b.HasIndex("ID_Genre");

                    b.ToTable("GenreFilms");

                    b.HasData(
                        new
                        {
                            ID = new Guid("034f32a9-64d9-42a5-90b6-f6497e7d7caf"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(8424), new TimeSpan(0, 0, 0, 0, 0)),
                            ID_Film = new Guid("98236a61-4d91-42fe-b956-fd64fb14ddc5"),
                            ID_Genre = new Guid("cd19b97d-2377-41bb-99dc-7db8314ff35e"),
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ID = new Guid("3abd8dcf-e6c4-49be-8272-d76e6c2e822c"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(8434), new TimeSpan(0, 0, 0, 0, 0)),
                            ID_Film = new Guid("d8a2e1e2-5d8c-4c4c-bf5f-9a7d32de0a2a"),
                            ID_Genre = new Guid("836c97c0-2ad2-4cd9-b821-537a8a872354"),
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Genres", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DeletedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            ID = new Guid("cd19b97d-2377-41bb-99dc-7db8314ff35e"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(8010), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GenreName = "Anime",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ID = new Guid("088f52ea-8a6d-4bb5-8bb8-2cd647e9b0f4"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(8021), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GenreName = "Chinese",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ID = new Guid("52048ea3-02c1-4c1c-81e0-0e5de6b16b07"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(8029), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GenreName = "Korea",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ID = new Guid("836c97c0-2ad2-4cd9-b821-537a8a872354"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(8033), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GenreName = "Romantic",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ID = new Guid("d5c9f4da-131e-47b6-b41f-a91409bb5d3a"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(8036), new TimeSpan(0, 0, 0, 0, 0)),
                            Deleted = false,
                            DeletedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            GenreName = "Action",
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Ratings", b =>
                {
                    b.Property<Guid>("ID_User")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_Film")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ID_User", "ID_Film");

                    b.HasIndex("ID_Film");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            ID_User = new Guid("f69cd789-4c44-401c-a021-5b6742af2279"),
                            ID_Film = new Guid("98236a61-4d91-42fe-b956-fd64fb14ddc5"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(8285), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Rating = 5
                        },
                        new
                        {
                            ID_User = new Guid("f69cd789-4c44-401c-a021-5b6742af2279"),
                            ID_Film = new Guid("d8a2e1e2-5d8c-4c4c-bf5f-9a7d32de0a2a"),
                            CreatedTime = new DateTimeOffset(new DateTime(2024, 7, 6, 13, 9, 33, 6, DateTimeKind.Unspecified).AddTicks(8294), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Rating = 5
                        });
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a884280c-dd19-4022-85bd-7105c59b27f9"),
                            ConcurrencyStamp = "f6b25b9e-5ef2-4aaf-9e9b-7ae4fdac2e2b",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("a040eef1-1d71-437e-ac64-e94d0b65c856"),
                            ConcurrencyStamp = "92ed2915-6aa0-4a86-8e7a-8f828d8d9e1f",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        });
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("SentTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e24d664c-e45f-4ddb-8743-04812e1ca9f5"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f6b25b9e-5ef2-4aaf-9e9b-7ae4fdac2e2b",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "dangs3007@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NormalizedEmail = "DANGS3007@GMAIL.COM",
                            NormalizedUserName = "DANGS",
                            PasswordHash = "AQAAAAEAACcQAAAAEKY9X1b1Y2X9z8x2C9jzFz2JbYfhLzzKm3Q/7+YpY6XjyONn6m8fJ6iM0Wb8PfFy1A==",
                            PhoneNumber = "123456789",
                            PhoneNumberConfirmed = true,
                            RoleId = new Guid("a884280c-dd19-4022-85bd-7105c59b27f9"),
                            SecurityStamp = "XQYOWUD3KZAC3K6A3OJ3M7NJI3J4D7YX",
                            TwoFactorEnabled = false,
                            UserName = "dangs"
                        },
                        new
                        {
                            Id = new Guid("84f0e463-e887-4143-a994-61ca73c4793c"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "92ed2915-6aa0-4a86-8e7a-8f828d8d9e1f",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "thend@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NormalizedEmail = "THEND@GMAIL.COM",
                            NormalizedUserName = "THEND",
                            PasswordHash = "AQAAAAEAACcQAAAAEKY9X1b1Y2X9z8x2C9jzFz2JbYfhLzzKm3Q/7+YpY6XjyONn6m8fJ6iM0Wb8PfFy1A==",
                            PhoneNumber = "987654321",
                            PhoneNumberConfirmed = true,
                            RoleId = new Guid("a884280c-dd19-4022-85bd-7105c59b27f9"),
                            SecurityStamp = "7S43J6OZ5E3H3Z2M3I2P8X7R7U5W2E7B",
                            TwoFactorEnabled = false,
                            UserName = "thend"
                        },
                        new
                        {
                            Id = new Guid("f69cd789-4c44-401c-a021-5b6742af2279"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7d1c77f2-9b7e-4f5d-b0e6-3d13c7a4cc09",
                            CreatedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "dangs123@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            ModifiedTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            NormalizedEmail = "DANGS123@GMAIL.COM",
                            NormalizedUserName = "CLIENTEST",
                            PasswordHash = "AQAAAAEAACcQAAAAEKY9X1b1Y2X9z8x2C9jzFz2JbYfhLzzKm3Q/7+YpY6XjyONn6m8fJ6iM0Wb8PfFy1A==",
                            PhoneNumber = "123456789",
                            PhoneNumberConfirmed = true,
                            RoleId = new Guid("a040eef1-1d71-437e-ac64-e94d0b65c856"),
                            SecurityStamp = "4b051b8e-4b64-4a2a-94e6-3f8a3b43b2c7",
                            TwoFactorEnabled = false,
                            UserName = "clienttest"
                        });
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.WatchedFilms", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan>("CurrentPosition")
                        .HasColumnType("time");

                    b.Property<Guid>("ID_Film")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_User")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ModifiedTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ID");

                    b.HasIndex("ID_Film");

                    b.HasIndex("ID_User");

                    b.ToTable("WatchedFilms");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginProvider", "UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Comments", b =>
                {
                    b.HasOne("FilmMoi.Domain.Models.Entities.Films", "Film")
                        .WithMany("Comments")
                        .HasForeignKey("ID_Film")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmMoi.Domain.Models.Entities.Users", "User")
                        .WithMany("Comments")
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Episodes", b =>
                {
                    b.HasOne("FilmMoi.Domain.Models.Entities.Films", "Film")
                        .WithMany("Episodes")
                        .HasForeignKey("ID_Film")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.FilmActors", b =>
                {
                    b.HasOne("FilmMoi.Domain.Models.Entities.Actors", "Actor")
                        .WithMany("filmActors")
                        .HasForeignKey("ID_ACtor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmMoi.Domain.Models.Entities.Films", "Film")
                        .WithMany("filmActors")
                        .HasForeignKey("ID_Film")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.GenreFilms", b =>
                {
                    b.HasOne("FilmMoi.Domain.Models.Entities.Films", "Film")
                        .WithMany("GenreFilms")
                        .HasForeignKey("ID_Film")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmMoi.Domain.Models.Entities.Genres", "Genre")
                        .WithMany("GenreFilms")
                        .HasForeignKey("ID_Genre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Ratings", b =>
                {
                    b.HasOne("FilmMoi.Domain.Models.Entities.Films", "Film")
                        .WithMany("Ratings")
                        .HasForeignKey("ID_Film")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmMoi.Domain.Models.Entities.Users", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Users", b =>
                {
                    b.HasOne("FilmMoi.Domain.Models.Entities.Roles", "Roles")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.WatchedFilms", b =>
                {
                    b.HasOne("FilmMoi.Domain.Models.Entities.Films", "Film")
                        .WithMany("WatchedFilms")
                        .HasForeignKey("ID_Film")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmMoi.Domain.Models.Entities.Users", "User")
                        .WithMany("WatchedFilms")
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Actors", b =>
                {
                    b.Navigation("filmActors");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Films", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Episodes");

                    b.Navigation("GenreFilms");

                    b.Navigation("Ratings");

                    b.Navigation("WatchedFilms");

                    b.Navigation("filmActors");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Genres", b =>
                {
                    b.Navigation("GenreFilms");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FilmMoi.Domain.Models.Entities.Users", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Ratings");

                    b.Navigation("WatchedFilms");
                });
#pragma warning restore 612, 618
        }
    }
}
